spring:
  datasource:
    url: jdbc:postgresql://bbapi.datvu.tech:5432/bbapidb
    username: bbapidb
    password: bbapidb
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://bbauth.datvu.tech/realms/beatbuddy/protocol/openid-connect/certs
          issuer-uri: https://bbauth.datvu.tech/realms/beatbuddy
  jpa:
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': false
        jdbc:
          '[time_zone]': UTC
        cache:
          '[use_second_level_cache]': false

    show-sql: true
  docker:
    compose:
      enabled: false
      skip:
        in-tests: true

# server:
#   port: ${PORT:8080}
#   server.ssl.key-store: ${TLS_FILE_PATH:/etc/tls/bbapi.datvu.tech/bbapi.datvu.tech.p12}
#   server.ssl.key-store-password: bbapi
#   server.ssl.keyStoreType: PKCS12
#   server.ssl.keyAlias: bbapi.datvu.tech

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

bbapi:
  server-url: https://bbauth.datvu.tech
  realm: beatbuddy
  grant-type: client_credentials
  client-id: bbapi
  client-secret: 2HmOZC4Y7XfhtPy43u6fdYKqLqnKaQcA