spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://beatbuddyapi.datvu.tech:5432/beatbuddyapidb}
    username: ${DB_USER:beatbuddyapidb}
    password: ${DB_PASS:beatbuddyapidb}
  flyway:
    baseline-on-migrate: true
    baseline-version: ${FLYWAY_BASELINE_VERSION:1}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI:http://beatbuddyauth.datvu.tech/realms/beatbuddy/protocol/openid-connect/certs}
      client:
        registration:
          beatbuddyapi:
            client-id: ${BEAT_BUDDY_API_CLIENT_ID:beatbuddyapi}
            client-secret: ${BEAT_BUDDY_API_CLIENT_SECRET:OlgAtZaj5SRia4YWBvKPok07rfGUKSoP}
            scope: openid
            authorization-grant-type: client_credentials
        provider: 
          beatbuddyapi: 
            token-uri: ${BEAT_BUDDY_API_TOKEN_URI:http://beatbuddyauth.datvu.tech/realms/beatbuddy/protocol/openid-connect/token}
  data:
    redis:
      host: ${REDIS_HOST:beatbuddyapiredis.datvu.tech}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:beatbuddyapiredis}
  cache:
    redis:
      cache-null-values: true
      time-to-live: 60000
    type: redis
    cache-names:
      - cache1
      - cache2
  jpa:
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": false
        jdbc:
          "[time_zone]": UTC
        cache:
          "[use_second_level_cache]": false
          
    show-sql: true
  docker:
    compose:
      enabled: false
      skip:
        in-tests: true
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger
app:
  service:
    beatbuddy-storage-url: ${BEAT_BUDDY_STORAGE_URL:http://beatbuddystorage.datvu.tech}
    # beatbuddy-storage-url: ${BEAT_BUDDY_STORAGE_URL:http://localhost:8081}
    beatbuddy-static-url: ${BEAT_BUDDY_STATIC_URL:http://beatbuddystatic.datvu.tech}
