spring:
  datasource:
    url: jdbc:postgresql://beatbuddy.io.vn:5432/bbapidb
    username: bbapidb
    password: bbapidb
  flyway:
    baseline-on-migrate: true
    baseline-version: 2
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://datvutech.io.vn/oauth/realms/beatbuddy/protocol/openid-connect/certs
          issuer-uri: https://datvutech.io.vn/oauth/realms/beatbuddy
  jpa:
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': false
        jdbc:
          '[time_zone]': UTC
        cache:
          '[use_second_level_cache]': false

    show-sql: true
  docker:
    compose:
      enabled: false
      skip:
        in-tests: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs


policy-enforcer:
  auth-server-url: https://datvutech.io.vn/oauth

bbapi:
  server-url: https://datvutech.io.vn/oauth
  realm: beatbuddy
  grant-type: client_credentials
  client-id: bbapi
  client-secret: SG01wIpg7l8FB4wxFVFVcFbfmJ8Wy7To