version: '3.7'
name: beatbuddy
services:
  # #: API
  apidb:
    image: postgres:16.1-bookworm
    hostname: apidb
    environment:
      - POSTGRES_DB=bbapidb
      - POSTGRES_USER=bbapidb
      - POSTGRES_PASSWORD=bbapidb
      - PGPASSWORD=bbapidb
    ports:
      - 5432:5432
    volumes:
      - bbapidb:/var/lib/postgresql/data/
      - ./api/db/initdb.d/:/docker-entrypoint-initdb.d/
      - ./api/db/backup/:/backup/
      - ./api/db/backup.sh:/backup.sh
    networks:
      - beatbuddy
  api:
    image: vutiendat3601/bbapi:1.0.0
    hostname: api
    environment:
      - DB_URL=jdbc:postgresql://apidb:5432/bbapidb
      - DB_USER=bbapidb
      - DB_PASS=bbapidb
      - SPRING_FLYWAY_BASELINE_VERSION=2
      - JWKS_URI=https://datvutech.io.vn/oauth/realms/beatbuddy/protocol/openid-connect/certs
      - PORT=8080
    ports:
      - 8080:8080
    volumes:
      - bbapi:/root/beatbuddy
    depends_on:
      - apiredis
      - apidb
    networks:
      - beatbuddy
  # API

  # #: Auth
  authdb:
    image: postgres:16.1-bookworm
    hostname: authdb
    environment:
      - POSTGRES_USER=bbauthdb
      - POSTGRES_DB=bbauthdb
      - POSTGRES_PASSWORD=bbauthdb
      - PGPASSWORD=bbauthdb
    volumes:
      - bbauthdb:/var/lib/postgresql/data/
      - ./auth/db/initdb.d/:/docker-entrypoint-initdb.d/
      - ./auth/db/backup/:/backup/
      - ./auth/db/backup.sh:/backup.sh
    networks:
      - beatbuddy
  auth:
    build: ./auth/
    # image: vutiendat3601/beatbuddyauth:1.0.0
    hostname: auth
    environment:
      - KC_DB_URL=jdbc:postgresql://authdb:5432/bbauthdb
      - KC_DB_USERNAME=bbauthdb
      - KC_DB_PASSWORD=bbauthdb
      - KC_HOSTNAME_URL=https://datvutech.io.vn/oauth
      - KC_HOSTNAME_ADMIN_URL=https://datvutech.io.vn/oauth
      - KC_HTTP_PORT=8090
      # - KC_PROXY=reencrypt
      - hostname-strict=false
      - KC_PROXY=edge
    depends_on:
      - authdb
    networks:
      - beatbuddy
    ports:
      - 8090
    command: ['start']
  # # Auth

  # ## Proxy
  proxy:
    image: nginx:mainline-bookworm
    hostname: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - auth
      - api
    networks:
      - beatbuddy
    healthcheck:
      test: curl http://api:8080 && curl http://auth:8090
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    restart: on-failure
volumes:
  bbapidb:
    name: bbapidb
    driver: local
  bbapi:
    name: bbapi
    driver: local
  bbauthdb:
    name: bbauthdb
    driver: local
networks:
  beatbuddy:
    name: beatbuddy
    driver: bridge
