version: '3.7'
name: beatbuddyproxy
services:
  nginx:
    image: nginx:mainline-bookworm
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - default

networks:
  default:
    name: beatbuddyproxy
    driver: host
